name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installation des dépendances Python
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Vérification de la qualité du code (flake8)
        run: |
          pip install flake8
          flake8 backend/app.py

